### ISSUE TITLE
Usage for online inference

### ISSUE THREAD

**Issue by silvada95** [uzh-rpg/ssms_event_cameras#11]
Hi,

Congrats on this amazing work, and thanks for sharing the code!

I am trying to create an online inference code using SSM as a detector. I am testing it with the "dat" files from the Prophesee's datasets for now. The code I am using has this format: 

         x = torch.from_numpy(np.clip(events["x"].astype(np.int16).copy(),0,width-1)).to(device)
         y = torch.from_numpy(np.clip(events["y"].astype(np.int16).copy(),0,height-1)).to(device)
         t = torch.from_numpy(events["t"].astype(np.int64)).to(device)
         p = torch.from_numpy(events["p"].astype(np.uint8).copy()).to(device)
       
        img = stacked_histogram(x, y, t, p, bins, height, width, device)
        img = img.view(1,img.shape[0],img.shape[1], img.shape[2]).to(torch.float32)

        img= nn.functional.interpolate(img,scale_factor = (new_scale[0] / height, new_scale[1] / width), mode = 'bilinear')

        output = module(img)

The "img" tensor has the format (1,20,256,320).

When I try to send it to the model like this, it gives me an error on the rearrange function from the maxvit_rnn.py code, suggesting that I should use the LxBxCxHxW format.

Then, I tried to reshape it to (1,1,20,256,320). However, now I get the following error:

"RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 1, 384, 8, 10]"

which seems to come from the detector stage, which receives the 5D "backbone_features" as an input.

Do you have any suggestions on how to avoid those errors?

**Comment by NikolaZubic** [comment]
Point is that for inference you should use RNN-like behaviour, stepwise inference.

During training we use a certain sequence length and compute output and hidden states in parallel because we want to make it faster to train overcoming the for loop of RNNs over the sequence length.

During inference, you take your model and utilize forward_rnn function which does inference step by step and that's what you want:
https://github.com/uzh-rpg/ssms_event_cameras/blob/master/RVT/models/layers/s5/s5_model.py#L287

Because during inference you want something that has this compact hidden state, but O(1) complexity.

So, that's the thing you have to change.

**Comment by yuyangpoi** [comment]
Bu = B_bar @ signal
         ~~~~~~^~~~~~~~
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [7680, 2] but got: [7680, 1].

**Comment by yuyangpoi** [comment]
when I use forward_rnn, there is a problem: 
Bu = B_bar @ signal
         ~~~~~~^~~~~~~~
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [7680, 2] but got: [7680, 1].

And we find when using  [forward_ssm]([https://github.com/uzh-rpg/ssms_event_cameras/blob/master/RVT/models/layers/s5/s5_model.py](https://github.com/uzh-rpg/ssms_event_cameras/blob/master/RVT/models/layers/s5/s5_model.py#L311) and set sequence_length equal to 1, the inference speed is much slower than lstm.
